name: manage-azure-policy-ba63d2dc
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_Virtual_Machines_Deploy-ASC-Defender-VMs/**'
#      - 'Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_Azure_Sql_Databases_Deploy-ASC-Defender-Sql/**'
#      - 'Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_Azure_App_Services_Deploy-ASC-Defender-AppSrv/**'
#      - 'Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_Storage_Accounts_Deploy-ASC-Defender-SA/**'
#      - 'Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_Sql_on_Virtual_Machines_Deploy-ASC-Defender-SQLVM/**'
#      - 'Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_AKS_Deploy-ASC-Defender-AKS/**'
#      - 'Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_ACR_Deploy-ASC-Defender-ACR/**'
#      - 'Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_AKV_Deploy-ASC-Defender-AKV/**'
#      - 'Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_DNS_Deploy-ASC-Defender-DNS/**'
#      - 'Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_ARM_Deploy-ASC-Defender-ARM/**'
#      - 'Deploy-ASC-Defender/policies/Deploy_Azure_Security_Center_Security_Contacts_Deploy-ASC-SecurityContacts/**'
#      - 'Deploy-ASC-Defender/policies/Deploy_export_to_Log_Analytics_workspace_for_Azure_Security_Center_data_ffb6f416-7bd2-4488-8828-56585fef2be9/**'
#      - .github/workflows/manage-azure-policy-ba63d2dc.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_ba63d2dc}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_Virtual_Machines_Deploy-ASC-Defender-VMs/**
          Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_Azure_Sql_Databases_Deploy-ASC-Defender-Sql/**
          Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_Azure_App_Services_Deploy-ASC-Defender-AppSrv/**
          Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_Storage_Accounts_Deploy-ASC-Defender-SA/**
          Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_Sql_on_Virtual_Machines_Deploy-ASC-Defender-SQLVM/**
          Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_AKS_Deploy-ASC-Defender-AKS/**
          Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_ACR_Deploy-ASC-Defender-ACR/**
          Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_AKV_Deploy-ASC-Defender-AKV/**
          Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_DNS_Deploy-ASC-Defender-DNS/**
          Deploy-ASC-Defender/policies/Deploy_Azure_Defender_for_ARM_Deploy-ASC-Defender-ARM/**
          Deploy-ASC-Defender/policies/Deploy_Azure_Security_Center_Security_Contacts_Deploy-ASC-SecurityContacts/**
          Deploy-ASC-Defender/policies/Deploy_export_to_Log_Analytics_workspace_for_Azure_Security_Center_data_ffb6f416-7bd2-4488-8828-56585fef2be9/**
