name: manage-azure-policy-f6b46a98
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/Deny_or_Deploy_and_append_TLS_requirements_and_SSL_enforcement_on_resources_without_Encryption_in_transit_Enforce-EncryptTransit/**'
#      - 'initiatives/Deny_or_Audit_resources_without_Encryption_with_a_customer-managed_key_(CMK)_Enforce-Encryption-CMK/**'
#      - 'initiatives/Deploy_SQL_Database_built-in_SQL_security_configuration_Deploy-Sql-Security/**'
#      - 'initiatives/Deploy_Diagnostic_Settings_to_Azure_Services_Deploy-Diag-LogAnalytics/**'
#      - 'initiatives/Deploy_Azure_Security_Center_configuration_Deploy-ASC-Config/**'
#      - 'initiatives/Public_network_access_should_be_disabled_for_PAAS_services_Deny-PublicEndpoints/**'
#      - .github/workflows/manage-azure-policy-f6b46a98.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_f6b46a98}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/Deny_or_Deploy_and_append_TLS_requirements_and_SSL_enforcement_on_resources_without_Encryption_in_transit_Enforce-EncryptTransit/**
          initiatives/Deny_or_Audit_resources_without_Encryption_with_a_customer-managed_key_(CMK)_Enforce-Encryption-CMK/**
          initiatives/Deploy_SQL_Database_built-in_SQL_security_configuration_Deploy-Sql-Security/**
          initiatives/Deploy_Diagnostic_Settings_to_Azure_Services_Deploy-Diag-LogAnalytics/**
          initiatives/Deploy_Azure_Security_Center_configuration_Deploy-ASC-Config/**
          initiatives/Public_network_access_should_be_disabled_for_PAAS_services_Deny-PublicEndpoints/**
