name: manage-azure-policy-19e269f8
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'Deny-Public-Endpoints/policies/Public_network_access_should_be_disabled_for_CosmosDB_Deny-PublicEndpoint-CosmosDB/**'
#      - 'Deny-Public-Endpoints/policies/Public_network_access_should_be_disabled_for_MariaDB_Deny-PublicEndpoint-MariaDB/**'
#      - 'Deny-Public-Endpoints/policies/Public_network_access_should_be_disabled_for_MySQL_Deny-PublicEndpoint-MySQL/**'
#      - 'Deny-Public-Endpoints/policies/Public_network_access_should_be_disabled_for_PostgreSql_Deny-PublicEndpoint-PostgreSql/**'
#      - 'Deny-Public-Endpoints/policies/Public_network_access_should_be_disabled_for_KeyVault_Deny-PublicEndpoint-KeyVault/**'
#      - 'Deny-Public-Endpoints/policies/Public_network_access_on_Azure_SQL_Database_should_be_disabled_Deny-PublicEndpoint-Sql/**'
#      - 'Deny-Public-Endpoints/policies/Public_network_access_onStorage_accounts_should_be_disabled_Deny-PublicEndpoint-Storage/**'
#      - 'Deny-Public-Endpoints/policies/Public_network_access_on_AKS_API_should_be_disabled_Deny-PublicEndpoint-Aks/**'
#      - .github/workflows/manage-azure-policy-19e269f8.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_19e269f8}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          Deny-Public-Endpoints/policies/Public_network_access_should_be_disabled_for_CosmosDB_Deny-PublicEndpoint-CosmosDB/**
          Deny-Public-Endpoints/policies/Public_network_access_should_be_disabled_for_MariaDB_Deny-PublicEndpoint-MariaDB/**
          Deny-Public-Endpoints/policies/Public_network_access_should_be_disabled_for_MySQL_Deny-PublicEndpoint-MySQL/**
          Deny-Public-Endpoints/policies/Public_network_access_should_be_disabled_for_PostgreSql_Deny-PublicEndpoint-PostgreSql/**
          Deny-Public-Endpoints/policies/Public_network_access_should_be_disabled_for_KeyVault_Deny-PublicEndpoint-KeyVault/**
          Deny-Public-Endpoints/policies/Public_network_access_on_Azure_SQL_Database_should_be_disabled_Deny-PublicEndpoint-Sql/**
          Deny-Public-Endpoints/policies/Public_network_access_onStorage_accounts_should_be_disabled_Deny-PublicEndpoint-Storage/**
          Deny-Public-Endpoints/policies/Public_network_access_on_AKS_API_should_be_disabled_Deny-PublicEndpoint-Aks/**
